### ISSUE TITLE
Playback tracking fails with VLC as external player

### ISSUE THREAD

**Issue by Doc-4** [jellyfin/jellyfin-android#1459]
### Describe the bug

Play any video with VLC selected as external player
Player will start at beginning, ignoring resume timestamp if one exists, closing the player will fail to save a resume location, with the error message "No valid external player detected, playback tracking disabled"

This bug isn't fully present on a version of the app I compiled myself from the latest source code, if VLC itself doesn't crash while closing it does track playback properly (had to be release version, nightlies on VLC website are compiled as debug and have a different app ID), but other bugs are present as the build isn't fully stable. Tracking partially works on the release build listed below if you have playback history enabled, it succeeds at starting in the right place but fails to write the new resume time, spawning the notification error. On the one I built from source, tracking works perfectly so long as playback history is enabled, and totally fails if disabled. It seems to work better if you haven't changed anything, changing settings back to default without clearing app storage also sometimes remains broken.

The VLC logcat is too long to fit, and the Jellyfin logcat is over 5000 lines (Comment is too long (maximum is 65536 characters).
It would probably be better to reproduce this yourself locally and find the excerpt of the log that's actually relevant, that part's a bit beyond me.

### Application version

2.6.2, VLC 3.5.4, also tested VLC 3.6.0 beta 3 built from source

### Where did you install the app from?

F-Droid

### Device information

Pixel 8 Pro, Oneplus 7T Pro

### Android version

Android 14, GrapheneOS 2024072800; Android 11, OxygenOS 11.0.9.1.HD01AA

### Jellyfin server version

10.9.8

### Which video player implementations does this bug apply to?

- [ ] Web player (default)
- [ ] Integrated player (ExoPlayer)
- [X] External player (VLC, mpv, MX Player)

**Comment by DevAgac** [comment]
Why is this issue closed? The issue is not even talked about let alone solved. I am going to open an issue about it.

**Comment by Doc-4** [comment]
I believe this ended up getting fixed at some point between then and today's latest VLC beta builds on their end, but I'd suggest reopening this issue if it comes back.
